from __future__ import annotations

STANDARD_EVENT_LABELS = {
    "artifact_read": "读取上下文",
    "action_started": "动作开始",
    "action_finished": "动作完成",
    "command_finished": "命令完成",
    "file_write": "写文件",
    "file_edit": "改文件",
    "agent_round_context": "轮次上下文",
    "agent_round_report": "轮次报告",
    "workspace_patch_apply": "补丁同步",
    "state_transition": "状态切换",
    "llm_stream_started": "模型流开始",
    "llm_text_delta": "模型流增量",
    "llm_assistant_message": "模型消息",
    "llm_turn_started": "模型轮开始",
    "llm_turn_finished": "模型轮结束",
    "llm_stream_completed": "模型流完成",
    "llm_stream_error": "模型流错误",
    "reviewer_decision": "审查判断",
    "validator_decision": "巡检判断",
    "error": "错误",
}

LLM_FEED_EVENT_TYPES = {
    "node_entered",
    "node_exited",
    "llm_turn_started",
    "llm_turn_finished",
    "agent_round_context",
    "agent_round_report",
    "artifact_read",
    "action_started",
    "command_finished",
    "file_write",
    "file_edit",
    "llm_stream_started",
    "llm_text_delta",
    "llm_assistant_message",
    "llm_stream_completed",
    "llm_stream_error",
    "reviewer_decision",
    "validator_decision",
    "error",
}

EVENT_TRANSLATION_MATRIX = {
    "direct_llm": {
        "llm_stream_started": "llm_stream_started",
        "llm_text_delta": "llm_text_delta",
        "llm_assistant_message": "llm_assistant_message",
        "llm_stream_completed": "llm_stream_completed",
        "llm_stream_error": "llm_stream_error",
    },
    "opencode": {
        "step_start": "llm_turn_started",
        "step_finish": "llm_turn_finished",
        "text": "llm_assistant_message",
        "tool_use:read": "artifact_read",
        "tool_use:glob": "artifact_read",
        "tool_use:todowrite": "agent_round_context",
        "tool_use:write": "file_write",
        "tool_use:edit": "file_edit",
        "tool_use:bash": "command_finished",
        "tool_use:*": "action_started",
        "error": "llm_stream_error",
    },
    "claude_code": {
        "stream_start": "llm_stream_started",
        "assistant_message": "llm_assistant_message",
        "thinking_delta": "llm_text_delta",
        "tool_use_started": "action_started",
        "tool_input_delta": "llm_text_delta",
        "stream_complete": "llm_stream_completed",
        "stream_error": "llm_stream_error",
    },
}
